version: '2'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'blstrco/codeclimate-test-reporter']
    volumes:
      - ".:/plugin:ro"
